### ISSUE TITLE
postfix mail relay masquerading

### ISSUE THREAD

**Issue by treydock** [treydock/puppet-reloadingdb#4]
Maybe this:

```yaml
profile::postfix::server::configs:
  masquerade_domains:
    value: 'reloadingdb.com'
```

Will almost certainly require DNS updates
